### ISSUE TITLE
Request: Add forks and star counts to project table

### ISSUE THREAD

**Issue by hahnicity** [gousiosg/github-mirror#10]
The project table does not include how many forks/stars the project has at a given time. It would be helpful to include this.

**Comment by gousiosg** [comment]
Actually, you can retrieve both:

* stars: `select * from watchers w, projects p where p.id = w.project_id and w.created_at < DATE('') and p.id=...`
* forks: `select * from projects p, projects p1 where p.id = p1.forked_from and p.created_at < DATE('') and p.id=...`

What are you missing?

**Comment by hahnicity** [comment]
That's a clever way to get forks thanks.

So you're using the watchers table to denote stargazers? I guess I am a little confused by the naming.

**Comment by gousiosg** [comment]
Stargazers used to be called watchers when GHTorrent started. The latest schema is described here: http://ghtorrent.org/relational.html
