### ISSUE TITLE
restore script doesn't allow change of storage engine

### ISSUE THREAD

**Issue by hahnicity** [gousiosg/github-mirror#11]
When I try to use InnoDB I get an error.

    (venv)greg@Ithilien:~/Documents/ecs260/dump/mod_dump$ ./ght-restore-mysql -uroot -proot -eInnoDB .
    ./ght-restore-mysql: illegal option -- e
    Invalid option: -
    Usage: ./ght-restore-mysql [-u dbuser ] [-p dbpasswd ] [-h dbhost] [-d database ] dump_dir

Am I doing something wrong here?

**Comment by DerekTBrown** [comment]
Try explicitly defining the -h and -d flags, and see if that fixes the issue.

**Comment by hahnicity** [comment]
This was related to a pull request I made. I should have closed this ticket after it was accepted
