### ISSUE TITLE
SQLite3::SQLException in the first attempt

### ISSUE THREAD

**Issue by legendtang** [gousiosg/github-mirror#15]
Have I done something wrong?

````
E:\github\github-mirror>ght-retrieve-repo -c config.yaml gousiosg github-mirror
Overriding configuration mirror_history_pages_back=5 with new value 1000
Database empty, running migrations from D:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/ghtorrent-0.11.1/lib/ghtorrent/migrations
Creating table users
Creating table projects
Creating table commits
Creating table commit_parents
Creating table followers
Adding organization descriminator field to table users
Updating users with default values
Creating table organization-members
Adding table commit comments
Adding table project members
Adding table watchers
Adding table pull requests
Adding table pull request history
Adding table pull request commits
Adding table pull request comments
Adding unique(name, owner) constraint to table projects
Create table project_commits
Migrating data from commits to project_commits
Adding table forks
Adding table issues
Adding issue history
SQLite3::SQLException: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
D:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3/database.rb:91:in `initialize'
````
The result is that only `user` appears in the MongoDB.

**Comment by gousiosg** [comment]
Did you install the gem or trying it from the git repository? With a fresh checkout from GitHub, I cannot replicate this. Can you try:
```
git clone https://github.com/gousiosg/github-mirror.git
cd github-mirror
ruby -Ilib bin/ght-retrieve-repo -c config.yaml.standalone gousiosg github-mirror
```

Also, I see you are running on Windows; as I do not have access to a Windows machine, could you perhaps try to debug it a bit (e.g. install a different version of sqlite or install mysql)?

**Comment by legendtang** [comment]
Both has been tested with the same result.

I will switch to MySQL to check if that works.

Georgios Gousios <notifications@github.com>于2016年1月9日周六 上午12:03写道：

> Did you install the gem or trying it from the git repository? With a fresh
> checkout from GitHub, I cannot replicate this. Can you try:
>
> git clone https://github.com/gousiosg/github-mirror.git
> cd github-mirror
> ruby -Ilib bin/ght-retrieve-repo -c config.yaml.standalone gousiosg github-mirror
>
> Also, I see you are running on Windows; as I do not have access to a
> Windows machine, could you perhaps try to debug it a bit (e.g. install a
> different version of sqlite or install mysql)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gousiosg/github-mirror/issues/15#issuecomment-170040422>
> .
>
-- 
Wensheng Tang
Computer Science and Technology,
Wuhan University
430079

**Comment by legendtang** [comment]
@gousiosg When I use mysql2, it show me similar exception:

````
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'issue_id PRIMARY KEY AUTO_INCREMENT, `event_id` Long NOT NULL, `issue_id` intege' at line 1
````

I presume there are something in the code not compatible with Windows

**Comment by legendtang** [comment]
AND this also presents on my Arch Linux environment. All steps followed, I have no idea whether I have done something wrong.

**Comment by gousiosg** [comment]
```
$gem list | grep sqlite
sqlite3 (1.3.7)

```

**Comment by gousiosg** [comment]
Ok, I managed to replicate it on Ubuntu 10.10, with Ruby 2.2.3 and `sqlite3-1.3.11`. Working on it...

**Comment by gousiosg** [comment]
It turns out that a newer version of `jeremyevans/sequel` (I was using `4.23` on my Mac) changed code generation for migrations. I 've tested with `4.30` and looks like it is working with both MySQL and SQLite.

**Comment by legendtang** [comment]
Yes, it works like a charm now. Thanks!
