### ISSUE TITLE
Not working when gem mongo upgraded to (2.2.1, 1.12.5)

### ISSUE THREAD

**Issue by legendtang** [gousiosg/github-mirror#17]
````
$ ruby -Ilib bin/ght-retrieve-repo -c config.yaml gousiosg github-mirror
Overriding configuration mirror_history_pages_back=5 with new value 1000
WARN, 2016-01-25T09:46:19+00:00, ghtorrent -- ghtorrent.rb: Transaction failed (1 ms)
uninitialized constant Mongo::ConnectionFailure
/home/legend/github-mirror/lib/ghtorrent/adapters/mongo_persister.rb:199:in `rescue in rescue_connection_failure'
````

It seems that mongodb were not specified version?

**Comment by gousiosg** [comment]
They changed the authentication routine and the query specification in `mongo` gem versions after 2.0. On the GHTorrent server, we are happily using 1.12.5. I think the Gemspec also forbids installing versions higher than 1.12.x.

I 'd welcome patches to move to 2.0.

**Comment by legendtang** [comment]
I mean when someone trys to update gems globally due to other projects' need, thus such as mongo would be installed both (2.x, 1.x), GHTorrent failed to determine which version is to be used even on 'git checkout' version installed from bundle.

However, another package `bson` did the same but they actually throw a notice to end user that we don't use `bson` v4.

**Comment by gousiosg** [comment]
I see. It is good Ruby practice to manage dependencies locally for each project. You can use tools like `rbenv` or `rvm` to achieve this. GHTorrent is working correctly with the specified dependency versions, so I am closing this.
