### ISSUE TITLE
Extremely high mongodb load

### ISSUE THREAD

**Issue by dollyexpise** [gousiosg/github-mirror#21]
It seems the insert conditions put a very high loads and some locks on mongodb.  Is there any suitable way to address this?

**Comment by gousiosg** [comment]
Did you check whether you have the necessary indexes created? See here the indexes to create:

https://github.com/gousiosg/github-mirror/blob/master/lib/ghtorrent/adapters/mongo_persister.rb#L23

You can check whether a collection, e.g. `events`, has any index using the following command at the MongoDB prompt:

```
mongo> db.events.getIndexes()
```

The code should auto-create them, but you never know...

**Comment by dollyexpise** [comment]
Exactly what I started doing, thanks for the correct list!
