### ISSUE TITLE
SQLite3::SQLException: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY

### ISSUE THREAD

**Issue by misJogi** [gousiosg/github-mirror#22]
Hi during run this command:  **ght-retrieve-repo user repo** I received followed error:

> Overriding configuration mirror_history_pages_back=5 with new value 1000
> Database empty, running migrations from /var/lib/gems/2.1.0/gems/ghtorrent-0.11.1/lib/ghtorrent/migrations
> Creating table users
> Creating table projects
> Creating table commits
> Creating table commit_parents
> Creating table followers
> Adding organization descriminator field to table users
> Updating users with default values
> Creating table organization-members
> Adding table commit comments
> Adding table project members
> Adding table watchers
> Adding table pull requests
> Adding table pull request history
> Adding table pull request commits
> Adding table pull request comments
> Adding unique(name, owner) constraint to table projects
> Create table project_commits
> Migrating data from commits to project_commits
> Adding table forks
> Adding table issues
> Adding issue history
> SQLite3::SQLException: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
> /var/lib/gems/2.1.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'

Can I resolve this problem?

**Comment by gousiosg** [comment]
This has been resolved in master. Until a release is pushed to RubyGems, you can do the following
```
git clone https://github.com/gousiosg/github-mirror.git
cd github-mirror
gem build ghtorrent.gemspec
gem install
```

or you can just use the code directly from the checkout like so:

```
ruby -Ilib bin/ght-retrieve-repo user repo 
```

**Comment by edwardmp** [comment]
Encountered same type of issue for both sqlite as mysql today. Would probably be a good idea to push a release..

**Comment by gousiosg** [comment]
Thanks for reporting this @edwardmp, can you please check again?

**Comment by edwardmp** [comment]
@gousiosg yep works, thanks
