### ISSUE TITLE
 Last update too recent?

### ISSUE THREAD

**Issue by legendtang** [gousiosg/github-mirror#24]
If a spider fails to get response from GitHub API in consequence of unstable network environment, or the GitHub API Server itself, the program exits in advance with no error or exception. But when I run  with the same config again, it says:
````
WARN, 2016-05-04T00:11:20+08:00, ghtorrent -- full_repo_retriever.rb: Last update too recent
````

Any way to resume the polling? I found the watcher data is pretty far from the real (watchers + starrers).

**Comment by gousiosg** [comment]
You can try the `-f` switch. The watchers should only match the stars in the current GitHub terminology.
