### ISSUE TITLE
PTY allocation request

### ISSUE THREAD

**Issue by sammy-SC** [gousiosg/github-mirror#32]
@gousiosg Hello,

after using the service for a while I get following response when running
`ssh -L 3306:web.ghtorrent.org:3306 ghtorrent@web.ghtorrent.org`
response:
`PTY allocation request failed on channel 2`

Therefore I can't connect to mysql database. 
MongoDB works fine.

Thanks

**Comment by gousiosg** [comment]
Should work now.
