### ISSUE TITLE
Query a repository's license

### ISSUE THREAD

**Issue by Hjdskes** [gousiosg/github-mirror#38]
Hi,

I'm currently doing research into developers' locations and the types of licenses they use. GHTorrent is a valuable source of information for me, but I noticed in the MySQL web interface that repositories' licenses are not currently retrieved / stored. Is this correct?

I can probably work around this by writing some code of my own, but I think it will be a valuable addition to GHTorrent. The only change that seems to be required is to provide a custom media type in the `Accept` header (`application/vnd.github.drax-preview+json`), see [GitHub's documentation](https://developer.github.com/v3/licenses). I noticed that just recently you added support for custom media types, so I hope this wouldn't be too much work.

Thank you for providing GHTorrent, it is already a valuable resource for me!

**Comment by gousiosg** [comment]
Hi @Hjdskes, did you try implementing the licensing stuff?

**Comment by Hjdskes** [comment]
No; I am unfamiliar with the code base and do not know Ruby. I also had a deadline to make, so I decided to work around it instead.
