### ISSUE TITLE
Missing torrents

### ISSUE THREAD

**Issue by craigcabrey** [gousiosg/github-mirror#4]
Hi,

Under 'Available Downloads', it says 'List of available torrents (Last dump date: 2014-11-29)' but there are no torrents listed.

Can you update the site with a list of available .torrent files?

Thanks!

**Comment by craigcabrey** [comment]
I just realized this is the wrong repo to open this issue one, so closing. Sorry about that.

**Comment by slang800** [comment]
I have the same issue (there are no torrents on http://ghtorrent.org/downloads.html) and don't know of any other repo to open this issue in. @craigcabrey - where did you move this issue to?

**Comment by craigcabrey** [comment]
@slang800 ghtorrent/ghtorrent.org#17

They don't distribute torrents anymore, just use a normal HTTP transfer.
