### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by gabrielcalegari** [gousiosg/github-mirror#41]
Hi!
I'm trying to download the mysql dump of February 2017 of 50 GB, but I'm getting error of reading bytes. I tried to download from different networks. Does the server kicking me out?

**Comment by gousiosg** [comment]
I am not sure what the problem is. I am not running the server myself (the data it is stored on an Azure container) so I am afraid I cannot check the logs. FWIW, I 've never had any download issues myself and nobody ever complained about this. Perhaps it was a temporary net issue?
