### ISSUE TITLE
MongoDB dumps from tudelft.nl unreachable

### ISSUE THREAD

**Issue by amintos** [gousiosg/github-mirror#42]
It seems like the two initial MongoDB dumps (hosted at TU Delft) have been unreachable for the past two weeks:

```
http://dutihr.st.ewi.tudelft.nl/downloads/commits-dump.2015-08-03.tar.gz
http://dutihr.st.ewi.tudelft.nl/downloads/commits-1-dump.2015-08-04.tar.gz
```

We encountered timeouts (no error response) using either wget or Firefox from both university and private IPs, although the host responds to ping. We had previously (a few months ago) downloaded both files successfully.

**Comment by Bhlowe** [comment]
Use this:
http://ghtorrent-downloads.ewi.tudelft.nl/mongo-full/

**Comment by amintos** [comment]
Thanks. Also, website links are up-to-date by now.
