### ISSUE TITLE
Cannot find user git@github.com:gousiosg/github-mirror.git.

### ISSUE THREAD

**Issue by kirshanluhana** [gousiosg/github-mirror#45]
ght-retrieve-repo  -c ~/config.yaml -s 'username' -p 'password'  git@github.com:gousiosg/github-mirror.git

fail to connect with 

g/github-mirror.git
Overriding configuration github_username=username with new value username
Overriding configuration github_passwd=password with new value password
Overriding configuration mirror_history_pages_back=5 with new value 1000
WARN, 2017-07-19T14:23:37+02:00, ghtorrent -- ghtorrent.rb: Not a valid email address: git@github.com:gousiosg/github-mirror.git
Error: Cannot find user git@github.com:gousiosg/github-mirror.git.
Try --help for help.

**Comment by gousiosg** [comment]
Try

```
ght-retrieve-repo -c ~/config.yaml -s 'username' -p 'password' gousiosg github-mirror.git
```

**Comment by kirshanluhana** [comment]
Thanks, it works perfect now. but I am not getting complete information for repo.
I am interested in Pull_request_comments but it is not fetching.

Also after very short period of time it gives error 

` ghtorrent -- api_client.rb: Request limit reached, reset in: 3554 secs
`
Trying from many days to dump data but files are too heavy to load and system fails.

Will appreciate your valuable guide.
Regards
