### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by sgoggins** [gousiosg/github-mirror#46]
I'm trying to get the files from ghtorrent.org/downloads, but I think they have moved. 

New Location in links:  https://ghtstorage.blob.core.windows.net/downloads/mysql-yyyy-mm-dd.tar.gz

However, the yyyy-mm-dd file is not there. I was not certain if this meant there was a file for everything, or if I need to do a wget for each file.

**Comment by sgoggins** [comment]
README under sql directory:

https://github.com/gousiosg/github-mirror/tree/master/sql

**Comment by gousiosg** [comment]
Sean, as far as I can tell, the following links work. What are you missing?

```
https://ghtstorage.blob.core.windows.net/downloads/mongo-dump-2017-07-30.tar.gz
https://ghtstorage.blob.core.windows.net/downloads/mysql-2017-07-01.tar.gz
```

`yyyy-mm-dd` is a pattern denoting a file at a specific date, I hope this was clear enough. I updated the README file to make it entirely clear.

**Comment by sgoggins** [comment]
In the readme for the SQL it was still pointing to the old link at http://ghtorrent.org/downloads … 

 

This file: https://github.com/gousiosg/github-mirror/blob/master/sql/README.md
