### ISSUE TITLE
Metadata appears out of date on several repos in MongoDB

### ISSUE THREAD

**Issue by colelloa** [gousiosg/github-mirror#47]
GHTorrent Team,

Black Duck Software has been hoping to use GHTorrent to keep up to date on all github metadata. When accessing using the MongoDB instance, we have noticed that several major repos appear to be somewhat out of date.

Using a few repos from owner 'google' as an example, but we've seen several major repos other than google being quite out of date:

1. google/material-design-lite

https://api.github.com/repos/google/material-design-lite
```
"stargazers_count": 28104,
"watchers_count": 28104,
```

> db.repos.find({ name: 'material-design-lite', 'owner.login': 'google'  })
```
   "stargazers_count": 12936,
   "watchers_count": 12936,

```

2. google/incremental-dom

https://api.github.com/repos/google/incremental-dom
```
"stargazers_count": 2684,
"watchers_count": 2684,
```

> db.repos.find({ name: 'incremental-dom', 'owner.login': 'google'  })
```
"stargazers_count":1314,
"watchers_count":1314,
```

3. google/binnavi

https://api.github.com/repos/google/binnavi
```
"stargazers_count": 2187,
"watchers_count": 2187,
```

> db.repos.find({ name: 'binnavi', 'owner.login': 'google'  })
```
   "stargazers_count":1183,
   "watchers_count":1183,
```

We at Black Duck were wondering if there was a way to identify repositories that have not been updated recently, and/or would like to help out the GHTorrent team in any way possible to stay as up to date as possible. Please reach out to us here on email me directly at acolello@blackducksoftware.com so we can try to find a solution that can benefit both of our organizations.

Best,
Andrew Colello
Software Engineer, Knowledgebase Team
Black Duck Software

**Comment by gousiosg** [comment]
What you describe is expected behaviour. GHTorrent uses MongoDB as a  cache to avoid querying GitHub over the same entities. The MySQL schema is where the state should be as close to GitHub as possible, but there are several issues (e.g GitHub does not emit "delete" events) that do not allow GHTorrent to be an exact replica.

**Comment by gousiosg** [comment]
WRT repos not being updated recently, what you need is a query (in MySQL/BigQuery) that will filter all projects that have not received any commits in the last 6 months or so, e.g.:

```sql
select p.id
from projects p, project_commits pc
where p.id  = pc.project_id
and not exists (
  select * 
  from commits c 
  where pc.commit_id = c.id 
  and c.created_at > date('2017/01/01') ) 
```

**Comment by gousiosg** [comment]
@colelloa Is this resolved? If yes, please close
