### ISSUE TITLE
MongoDB daily dumps seem to have stopped

### ISSUE THREAD

**Issue by kelewis** [gousiosg/github-mirror#48]
The last mongo-dump file is from 2017-07-30.
https://ghtstorage.blob.core.windows.net/downloads/mongo-dump-2017-07-30.tar.gz

**Comment by gousiosg** [comment]
Indeed. The `/scratch` directory used to create them got full. It should be fine now.

**Comment by kelewis** [comment]
Awesome.  Everything is back to normal.  Thanks Georgios!
