### ISSUE TITLE
Issues importing mysql data  -- Importing instructions

### ISSUE THREAD

**Issue by Jakobovski** [gousiosg/github-mirror#5]
Hi,

Thanks for the awesome project! 

I am having a hard time importing the massive mysql file. It starts out fast but after 20% or so the import speed drops significantly. It seems like it will never complete because the rate of import drops faster than the the progress.

I am wondering if you can include instructions in the readme/website of how to import the data.  Are there mysql config changes that i need to make? What are the min system requirements?

Thanks!

**Comment by gousiosg** [comment]
Honestly, I do not have any tips on how to import the MySQL dump other than wait. It is massive and it takes massive amount of time to import.  Generally, I follow the advice [here](http://serverfault.com/questions/146525/how-can-i-speed-up-a-mysql-restore-from-a-dump-file). 

For comparison, on my 12-core, 128GB server it takes about 28 hours.

**Comment by dspinellis** [comment]
Are table indices set up correctly when importing?

Also, consider using a beefy server for the import, and then downgrading to the one you'll normally use.  On the AWS cloud, I once did an expensive import on a server with a lot of memory (for $5.52/hour you can now get an AWS [d2.8xlarge](https://aws.amazon.com/blogs/aws/next-generation-of-dense-storage-instances-for-ec2/) instance with 36 vCPUs, 244 GiB RAM, 48 TB disk, 10 Gbps network), and then downgraded the instance to a server with 4GB of RAM for day-to-day operations.

**Comment by Jakobovski** [comment]
Thanks.

I am considering making large contributions to this project. Would it be possible to setup a phone call with one of you tonight to discuss some questions and possible ways that I can contribute?

**Comment by gousiosg** [comment]
Hi, let's take this offline. Please send me a brief email with your ideas.
