### ISSUE TITLE
Use of project_members.ext_ref_id field?

### ISSUE THREAD

**Issue by dufferzafar** [gousiosg/github-mirror#51]
What does this field contain? and where is it used?

https://github.com/gousiosg/github-mirror/blob/9a715e0cb1001869f39b60a30463a14a93b7c48a/sql/schema.sql#L324

**Comment by gousiosg** [comment]
Nothing; used to contain the MongoDB key for the record that "created" the corresponding entry in MySQL. It should be removed.
