### ISSUE TITLE
issue_events action check constraint causes transaction to fail

### ISSUE THREAD

**Issue by colelloa** [gousiosg/github-mirror#52]
During normal operation, ensure_issue_events fails with the following error:

`ERROR, 2017-10-27T13:40:21-04:00, ghtorrent -- ghtorrent.rb: PG::CheckViolation: ERROR:  new row for relation "issue_events" violates check constraint "issue_events_action_check"
DETAIL:  Failing row contains (831153782, 49, 27, head_ref_restored, null, 2016-10-20 20:01:36).
`

This error does not crash the app, but causes all later transactions to fail:

`WARN, 2017-10-27T13:40:21-04:00, ghtorrent -- ghtorrent.rb: Transaction failed (3245 ms)
ERROR, 2017-10-27T13:40:21-04:00, ghtorrent -- ghtorrent.rb: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
`

There are many different types of issue events: https://developer.github.com/v3/issues/events/#events-1

However, the type constraint only declares a few actions, but enforces a not null constraint regardless: https://github.com/gousiosg/github-mirror/blob/master/lib/ghtorrent/migrations/011_add_issues.rb#L30

The code itself does nothing to try to filter the "action" field: https://github.com/gousiosg/github-mirror/blob/master/lib/ghtorrent/ghtorrent.rb#L1597

My question:

What is preferable
a) expand the constraint, or drop it altogether, so that all issue events are allowed to be written?
or b) alter ensure_issue_events so that it won't attempt to write any events that would violate the constraint?

**Comment by gousiosg** [comment]
Thanks for the bug report.  As far as I can see in the main database, this does not result in any constraint being generated in MySQL. The [SQL schema](https://github.com/gousiosg/github-mirror/blob/master/sql/schema.sql#L229) we distribute with the dumps confirms this.

I think at this stage it is easier to just drop this constraint, by directly editing the migration file. I 've checked whether we can create a migration to drop this in a systematic manner, but it looks like we cannot as the constraint is unnamed.
