### ISSUE TITLE
Confusion in the schema of RDBMS

### ISSUE THREAD

**Issue by ayushidalmia** [gousiosg/github-mirror#7]
Hello,

This is regarding the schema given here:
http://ghtorrent.org/files/schema.pdf

The id key is used in many tables and I am unable to understand it clearly. Consider the following cases:

1. The primary key "id" used in projects table, is it the same field used in repo_labels or repo_milestones?  I am unable to understand how are projects and repos related in the schema. Semantically, a project can consist of many repositories in github. 

2. The repo_labels has two labels: id and repo_id. The project members has repo_id as one of the primary key while the project table does not refer to repo_id at all. 

3. Watchers and issues are associated with repo_id while commits are associated with project_id. The project table does not has project_id in its attribute list. 

I have imported the sql dump and had hoped that firing a few sql queries would resolve the confusion, but it hasn't. Please help! 

Thanks and Regards,
Ayushi

**Comment by gousiosg** [comment]
Hi, this in not an issue in the code. Will reply to you via email.

**Comment by ayushidalmia** [comment]
Thanks :+1:
