### ISSUE TITLE
Incorrect datetime value error when running ght-restore-pg

### ISSUE THREAD

**Issue by larsborn** [gousiosg/github-mirror#79]
Executing the `ght-restore-pg` on the data from 2018-09-01 gives (at least) the following two datetime related errors:
```
ERROR:  date/time field value out of range: "0000-00-00 00:00:00"
CONTEXT:  COPY commits, line 490174, column created_at: "0000-00-00 00:00:00"

ERROR:  date/time field value out of range: "0000-00-00 00:00:00"
CONTEXT:  COPY issues, line 1738, column created_at: "0000-00-00 00:00:00"
```
The Postgres field for datetime does not allow `0000-00-00 00:00:00` as a date. `pg_schema.sql` defines all `created_at` columns as `NOT NULL` which also makes a solution replacing those values with `NULL` infeasible.

I see the following solutions but wanted to check back with you before submitting a PR:
1. remove the `NOT NULL` constraint from the `created_at` columns
2. remove all lines with `0000-00-00 00:00:00` from the dataset
3. somehow pre-filter the affected lines in the import script (maybe with a trigger leveraging `NULLIF`)

For `commits.csv` 911947 rows are affected:
```
foo@bar:~/mysql-2018-09-01$ grep '0000-00-00 00:00:00' commits.csv | wc -l
```

For `issues.csv`, this issue (hehe) is very limited:
```
foo@bar:~/mysql-2018-09-01$ grep '0000-00-00 00:00:00' issues.csv
1783,1334,19546,\N,0,\N,"0000-00-00 00:00:00",5239
1197979,1191531,19546,\N,0,\N,"0000-00-00 00:00:00",3
1391006,1191531,19546,\N,0,\N,"0000-00-00 00:00:00",2
58284114,77099772,1505119,\N,0,\N,"0000-00-00 00:00:00",9
```

**Comment by gousiosg** [comment]
I 've noticed this as well. This is caused because MariaDB, currently GHTorrent's main database, does not correctly handle dates that are `< 0` in epoch seconds. I have since changed the source code (19a2dedf28935d84) to make sure that no zero values are being written to any `created_at` field, and updated all corresponding entries in the database.  I think that the first dump that will contain those fixes will be the 2018-12-01. 

In the mean time, you can simply replace the incorrect values with a simple `sed` command, e.g.

```bash
sed -e 's/0000-00-00 00:00:00/1970-01-02/' < commits.csv
```

**Comment by amintos** [comment]
The same problem seems to affect 2019-06-01. For now, I successfully adopted @larsborn's solution, which appears to be cleaner than substituting with a placeholder date. From the point where the script breaks:

1. Substitute with null: `sed -i 's/"0000-00-00 00:00:00"/\\N/g' commits.csv`
2. Drop constraint: `ALTER TABLE commits ALTER COLUMN created_at DROP NOT NULL;`
3. Re-import with `COPY commits FROM 'mysql-2019-06-01/commits.csv' WITH (FORMAT 'csv', QUOTE E'"', ESCAPE '\', NULL '\N');`

(Ended up with `1368235072` commits, in case someone wants to verify)
